{{- if eq .Values.pv.createPV true -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.pv.storageClassName }}
  capacity:
    storage:  {{ .Values.pv.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.mountPath }}
{{- end -}}